"""호환 facade — 설정 영속의 정본은 :mod:`hwpxfiller.external.settings` 이다."""

from __future__ import annotations

from hwpxfiller.external.settings import (
    BOOT_STAMP_UNKNOWN_VERSION,
    DEFAULT_MASTER_WIDTH,
    MAX_MASTER_WIDTH,
    MIN_MASTER_WIDTH,
    PROPORTIONAL_DRAFT_FONTS,
    VALID_DRAFT_FONTS,
    VALID_FONT_SCALES,
    VALID_TEMPLATE_MEDIA,
    VALID_THEMES,
    _check_media,
    _settings_path,
    alert,
    home_dir,
    is_proportional_font,
    load_boot_completed,
    load_draft_target_font,
    load_font_scale,
    load_job_collapsed_groups,
    load_master_width,
    load_template_collapsed_groups,
    load_template_group_map,
    load_theme,
    load_window_geometry,
    save_boot_completed,
    save_draft_target_font,
    save_font_scale,
    save_job_collapsed_groups,
    save_master_width,
    save_template_collapsed_groups,
    save_template_group_map,
    save_template_group_state,
    save_theme,
    save_window_geometry,
)

__all__ = (
    "VALID_THEMES",
    "VALID_FONT_SCALES",
    "DEFAULT_MASTER_WIDTH",
    "MIN_MASTER_WIDTH",
    "MAX_MASTER_WIDTH",
    "VALID_DRAFT_FONTS",
    "PROPORTIONAL_DRAFT_FONTS",
    "BOOT_STAMP_UNKNOWN_VERSION",
    "VALID_TEMPLATE_MEDIA",
    "is_proportional_font",
    "alert",
    "home_dir",
    "load_theme",
    "save_theme",
    "load_font_scale",
    "save_font_scale",
    "load_master_width",
    "save_master_width",
    "load_window_geometry",
    "save_window_geometry",
    "load_draft_target_font",
    "save_draft_target_font",
    "load_boot_completed",
    "save_boot_completed",
    "load_job_collapsed_groups",
    "save_job_collapsed_groups",
    "load_template_group_map",
    "save_template_group_map",
    "load_template_collapsed_groups",
    "save_template_collapsed_groups",
    "save_template_group_state",
)
